### ISSUE TITLE
Possible faster extdata loading ?

### ISSUE THREAD

**Issue by coc4tm** [Hikiruka/Yuki-FM#5]
New 3DS
11.0E
MenuHax 3.0
Latest Yuki-FM build

**Comment by Wolvan** [comment]
Can confirm long loading times
Old 3ds, Firmware 11.0E
Sysnand CFW
Yuki-FM Nightly build (.cia) 99f6b51

**Comment by Hikiruka** [comment]
Solution I can give is booting ExtData mode from another index.lua. LPP-3DS still needs to read the Ext Data first, BUT load it once while Yuki FM is active = faster loading

**Comment by Wolvan** [comment]
Honestly, I'd suggest printing something like "Loading ExtData, this might take a while" to the screen so users know that it doesn't crash but just has long loading times

**Comment by Hikiruka** [comment]
Yeah, but then again putting an actual screen may delay the boot. I'll keep this open and see if anyone wants to suggest anything else

**Comment by Wolvan** [comment]
>Putting an actual screen

You mean printing the message that the thing is currently loading? That shouldn't delay anything too much. Is it quicker to load ExtData on App load?

**Comment by Hikiruka** [comment]
well yeah because then you dont have to worry about it the slower times for when you need it. Also I cant see why you'd use extdata mode over yellows8's ext data tool unless you use it for convinience

**Comment by Wolvan** [comment]
Yeah, but loading the extdata on boot makes the startup of the app lag. We at least have to give the users some kind of notification that extdata is being read

**Comment by Hikiruka** [comment]
fair enough
