### ISSUE TITLE
 new Banner/Icon ?

### ISSUE THREAD

**Issue by Hikiruka** [Hikiruka/Yuki-FM#8]
![image](https://cloud.githubusercontent.com/assets/12451040/18029339/82332964-6c63-11e6-9972-b442a22fe87e.png)
how's this for a shitty banner or does  it need improvement

**Comment by Wolvan** [comment]
Looks OK to me. If you want I can give it the rounded corners that the current placeholder icon has, just upload the PNG file somewhere

**Comment by Hikiruka** [comment]
![download](https://cloud.githubusercontent.com/assets/12451040/18029358/13d0a888-6c64-11e6-9b65-553855f61986.png)
done
